# Generated by Django 5.1.1 on 2024-09-13 15:27

from django.db import migrations
import os

def create_data(apps, schema_editor):
    content = apps.get_model('CartManage', 'Cart')
    content(money=0).save()


def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SU_NAME = os.getenv('DJANGO_NAME')
        DJANGO_SU_EMAIL = os.getenv('DJANGO_EMAIL')
        DJANGO_SU_PASSWORD = os.getenv('DJANGO_PASS')

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD)

        superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('CartManage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
        # migrations.RunPython(generate_superuser),
    ]